### PR TITLE
 Do not set ServiceLocator by RhinoSecurityInstaller, this is not his duty

### PR DESCRIPTION
**Pull request by whut**
Do not set ServiceLocator by RhinoSecurityInstaller, this is not his duty

Also updated How to Use.txt, to mention the Castle Windsor installer and example configuration of ServiceLocator

### CODE REVIEW

**Comment by whut** [comment]
I added also updated nuspec file, that removes dependency on log4net, that was removed some time ago from Rhino Security

**Comment by whut** [comment]
Also added ability to set Permission instance used by FluentPermissionBuilder, I need that to use my custom subclass of Permission

**Comment by whut** [comment]
Thanks. As a side note, could you publish official Rhino Security nuget to nuget.org?

**Comment by nrstott** [comment]
I've actually never published rhino security to nuget before.  If there is
a package for it, then it's not one that I maintain.

**Pull request merged**
